export enum ActionTypes {
  UPDATE_PASSWORD_FILTERS = "UPDATE_PASSWORD_FILTERS",
  UPDATE_CHARACTERS = "UPDATE_CHARACTERS",
  GENERATE_PASSWORD = "GENERATE_PASSWORD",
  SHOW_MODAL = "SHOW_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
}
